evaluation1Serveur-web/src/main/java/tn/esprit/javaee/evaluation1Serveur/presentation/mbeans/DeviceBean.java
package tn.esprit.javaee.evaluation1Serveur.presentation.mbeans;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import tn.esprit.javaee.evaluation1Serveur.persistence.Brand;
import tn.esprit.javaee.evaluation1Serveur.persistence.Device;
import tn.esprit.javaee.evaluation1Serveur.persistence.DeviceType;
import tn.esprit.javaee.evaluation1Serveur.persistence.Employee;
import tn.esprit.javaee.evaluation1Serveur.services.DeviceService;

@ManagedBean
@SessionScoped
public class DeviceBean {
	private String uniqueIdentifier;
	private DeviceType deviceType;
	private String modelName;
	private Brand brand;
	private Employee employee;
	private Long selectedEmployeeMatricule;
    
	@EJB
	DeviceService deviceService;

	
	public String addDevice(){
		String navigateTo="null";
	    deviceService.ajouterDevice(new Device(uniqueIdentifier, deviceType, modelName, brand));	
		return navigateTo;
	}
	
	public String affDevice(){
		String navigateTo="null";
	    deviceService.affecterDeviceAEmployee(uniqueIdentifier, selectedEmployeeMatricule);
		return navigateTo;
	}
	
	public Long getSelectedEmployeeMatricule() {
		return selectedEmployeeMatricule;
	}
	
	public void setSelectedEmployeeMatricule(Long selectedEmployeeMatricule) {
		this.selectedEmployeeMatricule = selectedEmployeeMatricule;
	}

	public String getUniqueIdentifier() {
		return uniqueIdentifier;
	}
	public void setUniqueIdentifier(String uniqueIdentifier) {
		this.uniqueIdentifier = uniqueIdentifier;
	}
	public DeviceType getDeviceType() {
		return deviceType;
	}
	public void setDeviceType(DeviceType deviceType) {
		this.deviceType = deviceType;
	}
	public String getModelName() {
		return modelName;
	}
	public void setModelName(String modelName) {
		this.modelName = modelName;
	}
	public Brand getBrand() {
		return brand;
	}
	public void setBrand(Brand brand) {
		this.brand = brand;
	}
	public Employee getEmployee() {
		return employee;
	}
	public void setEmployee(Employee employee) {
		this.employee = employee;
	}
	
}

evaluation1Serveur-web/src/main/java/tn/esprit/javaee/evaluation1Serveur/presentation/mbeans/EmployeeBean.java
package tn.esprit.javaee.evaluation1Serveur.presentation.mbeans;

import java.util.List;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;

import tn.esprit.javaee.evaluation1Serveur.persistence.Device;
//import tn.esprit.javaee.evaluation1Serveur.persistence.Device;
import tn.esprit.javaee.evaluation1Serveur.persistence.Employee;
import tn.esprit.javaee.evaluation1Serveur.persistence.EmployeeType;
import tn.esprit.javaee.evaluation1Serveur.services.EmployeeService;

@ManagedBean
@SessionScoped

public class EmployeeBean {
	private Long matricule;
	private String firstName;
	private String lastName;
	private String password;
	private EmployeeType employeeType;
	private List<String> devicesUniqueIdentifiers;
	private List<Device> devices;
	@EJB
	EmployeeService employeeService;
	private List<Employee> employees;
	private List<String> employeeNames;
	private List<Long> employeesMatricules;
	////////// @ManagedProperty(value = "#{loginBean}")
////////	  private LoginBean loginBean;
//	public List<Device> getDevices() {
//		return employeeService.getAllEmployeeDevices(matricule);
//		//return employeeService.getAllEmployeeDevices(getMatricule());
//		//return employeeService.getAllEmployeeDevices(loginBean.getEmployee().getMatricule());
//	}

	public void setDevices(List<Device> devices) {
		this.devices = devices;
	}

//	public List<Long> getEmployeesMatricules() {
//		List<Long> employeesMatricules = employeeService.getAllEmployeMatriculesJPQL();
//		return employeesMatricules;
//	}

	public void setEmployeesMatricules(List<Long> employeesMatricules) {
		this.employeesMatricules = employeesMatricules;
	}

//	public List<String> getEmployeeNames() {
//		List<String> employeeNames = employeeService.getAllEmployeNamesJPQL();
//		return employeeNames;
//	}

	public void setEmployeeNames(List<String> employeeNames) {
		this.employeeNames = employeeNames;
	}

//	public List<Employee> getEmployees() {
//		employees = employeeService.getAllEmployees();
//		return employees;
//	}
	
	public void setEmployees(List<Employee> employees) {
		this.employees = employees;
	}

	public Long getMatricule() {
		return matricule;
	}
	public void setMatricule(Long matricule) {
		this.matricule = matricule;
	}
	public String getFirstName() {
		return firstName;
	}
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	public String getLastName() {
		return lastName;
	}
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public EmployeeType getEmployeeType() {
		return employeeType;
	}
	public void setEmployeeType(EmployeeType employeeType) {
		this.employeeType = employeeType;
	}

	public String addEmployee(){
		String navigateTo="null";
	//public void addEmploye(){
//		employeService.ajouterEmploye(new Employe(nom, prenom, email,role, isActif));
		// Employe(String nom, String prenom, String email, boolean isActif)
		
		employeeService.ajouterEmployee(new Employee(firstName, lastName, password, employeeType));

		//navigateTo = "/login?faces-redirect=true";
	// navigateTo = "/pages/welcome?faces-redirect=true";
		return navigateTo;
	}
	
//	public List<String> getDevicesUniqueIdentifiers() {
//		devicesUniqueIdentifiers = employeeService.getAllEmployeeDeviceUniqueIdentifiersJPQL(matricule);
////		devicesUniqueIdentifiers = employeeService.getAllEmployeeDeviceUniqueIdentifiersJPQL(loginBean.getEmployee().getMatricule());
//		return devicesUniqueIdentifiers;
//	}

	public void setDevicesUniqueIdentifiers(List<String> devicesUniqueIdentifiers) {
		this.devicesUniqueIdentifiers = devicesUniqueIdentifiers;
	}
		
	}

evaluation1Serveur-web/src/main/java/tn/esprit/javaee/evaluation1Serveur/presentation/mbeans/LoginBean.java
package tn.esprit.javaee.evaluation1Serveur.presentation.mbeans;

import java.util.List;

import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

import tn.esprit.javaee.evaluation1Serveur.persistence.Device;
import tn.esprit.javaee.evaluation1Serveur.persistence.Employee;
import tn.esprit.javaee.evaluation1Serveur.persistence.EmployeeType;
import tn.esprit.javaee.evaluation1Serveur.services.DeviceService;
import tn.esprit.javaee.evaluation1Serveur.services.EmployeeService;

@ManagedBean
@SessionScoped
public class LoginBean {
private Long login;
private String password;
private Employee employee;
private boolean loggedIn;
private Long selectedEmployeId;
private String selectedDeviceId;


@EJB
EmployeeService employeeService;

@EJB
DeviceService deviceService;

public String doLogin(){
	String navigateTo="null";
	employee = employeeService.getEmployeeByMatriculeAndPassword(login, password);
    if (employee !=null){
    	loggedIn=true;
	if (employee.getEmployeeType()==EmployeeType.ADMIN){
		navigateTo="/espaceadmin?faces-redirect=true";
	}
	if (employee.getEmployeeType()==EmployeeType.EMP){
		navigateTo="/espacemployee?faces-redirect=true";
	}
    }
	else {
		FacesContext.getCurrentInstance().addMessage("form:btn", new FacesMessage("bad credentials"));
	}
return navigateTo;
}


public void affecterDeviceAEmploye(){
	deviceService.affecterDeviceAEmployee(selectedDeviceId, selectedEmployeId);
}


public String doLogout(){
	FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
	return "/login?faces-redirect=true";
}

public List<Device> getDevicesByEmploye() {
	return employeeService.getDevicesByEmploye(employee.getMatricule()); //getAllEmployeeDevices(employee.getMatricule());
	//return employeeService.getAllEmployeeDevices(getMatricule());
	//return employeeService.getAllEmployeeDevices(loginBean.getEmployee().getMatricule());
}


public List<Employee> getAllEmployees() {
	return employeeService.getAllEmploye();
}


public List<Device> getAllDevices(){
	return deviceService.getAllDevices();
}


public Long getSelectedEmployeId() {
	return selectedEmployeId;
}



public void setSelectedEmployeId(Long selectedEmployeId) {
	this.selectedEmployeId = selectedEmployeId;
}



public String getSelectedDeviceId() {
	return selectedDeviceId;
}



public void setSelectedDeviceId(String selectedDeviceId) {
	this.selectedDeviceId = selectedDeviceId;
}



public EmployeeService getEmployeeService() {
	return employeeService;
}



public void setEmployeeService(EmployeeService employeeService) {
	this.employeeService = employeeService;
}



public DeviceService getDeviceService() {
	return deviceService;
}



public void setDeviceService(DeviceService deviceService) {
	this.deviceService = deviceService;
}


public String getPassword() {
	return password;
}

public void setPassword(String password) {
	this.password = password;
}


public boolean isLoggedIn() {
	return loggedIn;
}

public void setLoggedIn(boolean loggedIn) {
	this.loggedIn = loggedIn;
}

public Long getLogin() {
	return login;
}

public void setLogin(Long login) {
	this.login = login;
}

public Employee getEmployee() {
	return employee;
}
public void setEmployee(Employee employee) {
	this.employee = employee;
}

}

evaluation1Serveur-web/src/main/webapp/espaceadmin.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
       xmlns:f="http://xmlns.jcp.org/jsf/core"
	   xmlns:h="http://xmlns.jcp.org/jsf/html"
	   xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	   xmlns:jsf="http://xmlns.jcp.org/jsf"
	   xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	   xmlns:p="http://primefaces.org/ui">

	
	<h:head>.....WELCOME #{loginBean.employee.firstName} #{loginBean.employee.lastName}...
	</h:head>
	<h:body>
	<h:form  id="form2">
	
		<h:commandButton id="btnlogout" action="#{loginBean.doLogout()}" value="logout" />
	<h:message for="btnlogout"/>

	<br/>

		<h:selectOneMenu value="#{loginBean.selectedDeviceId}" >
			<f:selectItems value="#{loginBean.allDevices}" 
				var="device" itemValue="#{device.uniqueIdentifier}" 
				itemLabel="#{device}" />
		</h:selectOneMenu>
		
		<h:selectOneMenu value="#{loginBean.selectedEmployeId}" >
			<f:selectItems value="#{loginBean.allEmployees}" 
				var="employe" itemValue="#{employe.matricule}" 
				itemLabel="#{employe}" />
		</h:selectOneMenu>
		
		<h:commandButton id="btn" action="#{loginBean.affecterDeviceAEmploye()}" value="Affecter" />
		
	<br/>
	
		</h:form>
	
	<ui:include src="/template/footer.xhtml" />
	 </h:body>
</html>

evaluation1Serveur-web/src/main/webapp/espacemployee.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
       xmlns:f="http://xmlns.jcp.org/jsf/core"
	   xmlns:h="http://xmlns.jcp.org/jsf/html"
	   xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	   xmlns:jsf="http://xmlns.jcp.org/jsf"
	   xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	   xmlns:p="http://primefaces.org/ui">

	
	<h:head>.....WELCOME #{loginBean.employee.firstName} #{loginBean.employee.lastName}...
	</h:head>
	<h:body>
	<h:form  id="form3">
	
		<h:commandButton id="btnlogout" action="#{loginBean.doLogout()}" value="logout" />
	<h:message for="btnlogout"/>

		<br/>
	<h:dataTable value="#{loginBean.employee.devices}" var="device" border="1">
	  <h:column>
	     <f:facet name="header">
	         <h:outputText value="Device Unique Identifier" />
	     </f:facet>
	     <h:outputText value="#{device.uniqueIdentifier}" />
	  </h:column>
	  	  <h:column>
	     <f:facet name="header">
	         <h:outputText value="Model Name" />
	     </f:facet>
	     <h:outputText value="#{device.modelName}" />
	  </h:column>
	</h:dataTable>

	<br/>
	</h:form>

	<ui:include src="/template/footer.xhtml" />
	</h:body>
</html>

evaluation1Serveur-web/src/main/webapp/login.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
       xmlns:f="http://xmlns.jcp.org/jsf/core"
	   xmlns:h="http://xmlns.jcp.org/jsf/html"
	   xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	   xmlns:jsf="http://xmlns.jcp.org/jsf"
	   xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	   xmlns:p="http://primefaces.org/ui">

	<h:head>
	<ui:include src="/template/header.xhtml" />
	<title>Bonjour Esprit</title></h:head>
	<h:body>
	<h:form id="form">
	<h:panelGrid columns="2">
	<h:outputText value="login (matricule)" />
	<h:inputText value="#{loginBean.login}" />
	<h:outputText value="password" />
	<h:inputSecret value="#{loginBean.password}" />
	<h:commandButton id="btn" action="#{loginBean.doLogin()}" value="login" />
	<h:message for="btn"/>
	</h:panelGrid>
	
	</h:form>
	<ui:include src="/template/footer.xhtml" />
	 </h:body>
</html>